
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class MainMenu extends javax.swing.JFrame {

    FrmCL frmCL;
    FrmCW frmCW;
    static String userType;

    /**
     * Creates new form MainMenu
     */
    public MainMenu(String inpUserType) {
        super();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpShow = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        COM = new javax.swing.JMenu();
        CLW = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpShowLayout = new javax.swing.GroupLayout(dpShow);
        dpShow.setLayout(dpShowLayout);
        dpShowLayout.setHorizontalGroup(
            dpShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        dpShowLayout.setVerticalGroup(
            dpShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        COM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budget.png"))); // NOI18N
        COM.setText("Comparison of Matrix ");
        COM.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        COM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        COM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        COM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COMMouseClicked(evt);
            }
        });
        jMenuBar2.add(COM);

        CLW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rut.png"))); // NOI18N
        CLW.setText("Calculating water");
        CLW.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        CLW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CLW.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CLW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLWMouseClicked(evt);
            }
        });
        jMenuBar2.add(CLW);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpShow)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COMMouseClicked
         frmCL = new FrmCL();
        this.dpShow.add(frmCL);
        frmCL.setVisible(true);
        frmCL.setSize(this.getSize());


        // TODO add your handling code here:
    }//GEN-LAST:event_COMMouseClicked

    private void CLWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLWMouseClicked
        frmCW = new FrmCW();
        this.dpShow.add(frmCW);
        frmCW.setVisible(true);
        frmCW.setSize(this.getSize());

        // TODO add your handling code here:
    }//GEN-LAST:event_CLWMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu(userType).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CLW;
    private javax.swing.JMenu COM;
    private javax.swing.JDesktopPane dpShow;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
